module.exports = {
    add: require('./add'),
    orderInfo: require('./orderInfo'),
    delete: require('./delete'),
    findOne: require('./findOne'),
    getCount: require('./getCount'),
    list: require('./list'),
    listForSelect: require('./listForSelect'),
    login: require('./login'),
    update: require('./update'),
    ordersEachClient: require('./ordersEachClient'),
    clientForPayment: require('./clientForPayment'),
    findOnePayment: require('./findOnePayment'),
    findShop: require('./findShop'),
    findUsername: require('./findUsername'),
};