module.exports = {
    add: require('./add'),
    delete: require('./delete'),
    findOne: require('./findOne'),
    getCount: require('./getCount'),
    getCountStorage: require('./getCountStorage'),
    list: require('./list'),
    listStorage: require('./listStorage'),
    update: require('./update'),
    updateStatus: require('./updateStatus'),
    saveOrder: require('./saveOrder'),
    countOrderInDistrict: require('./countOrderInDistrict'),
    countOrderInStatus: require('./countOrderInStatus'),
    countOrderInAllStatus: require('./countOrderInAllStatus'),
    orderForDelivery: require('./orderForDelivery'),
    orderForRefund: require('./orderForRefund'),
    changeMulti: require('./changeMulti'),
};