module.exports = {
    Counter: require('./counter.model'),
    Client: require('./client.model'),
    District: require('./district.model'),
    Order: require('./order.model'),
    Province: require('./province.model'),
    User: require('./user.model'),
    Ward: require('./ward.model'),
    Post: require('./post.model'),
    Role: require('./role.model'),
    Price: require('./price.model'),
    Refund: require('./refund.model'),
    History: require('./history.model'),
    Payment: require('./payment.model'),
};